version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${SQL_DATABASE:-theenglishcrab}
      MYSQL_USER: ${SQL_USER:-squid}
      MYSQL_PASSWORD: ${SQL_PASSWORD:-your_mysql_password}
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD:-your_root_password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
