name: Build and deploy Node.js app to Azure Web App - bg-blog-tic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Run Database Migrations
        run: |
          npx typeorm migration:run -d ./dist/data-source.js
        env:
          NODE_ENV: production
          SQL_HOST: ${{ secrets.SQL_HOST }}          # e.g., your Azure MySQL host: "yourserver.mysql.database.azure.com"
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}  # e.g., "theenglishcrab"
          SQL_USER: ${{ secrets.SQL_USER }}          # e.g., "squid@yourserver"
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}  # your MySQL password
          SQL_PORT: '3306'

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C07EB90413341CCB012C30453861509 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A67C6BE17004FDAA6E954674F09443A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D18C0ABC2115471194E66CFF4FA6B2FE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bg-blog-tic'
          slot-name: 'Production'
          package: .
